### ISSUE TITLE
Update Readme to address the recent removal of ABE schemes from Craco

### ISSUE THREAD

**Issue by rheitjoh** [cryptimeleon/craco#34]
The Craco readme still mentions that its main focus are attribute based schemes and that it implements several of them. This should be changed to better fit the current purpose of Craco.

**Comment by rheitjoh** [comment]
A little write-up of my thoughts formed over the last 30 minutes:

## Existing Examples
A good example mentioned by @feidens would be the [Circl page](https://github.com/cloudflare/circl).
Some features of the readme there:
- Badges indicating status of tests and code coverage
- Short overview of what the library offers and what its purpose / goal is
- a security disclaimer
- a succinct "how to install"
- mentions how the version numbers work
- what is implemented in more detail
- info on contributing and the license

Another example is the [Hyperledger page](https://github.com/hyperledger/ursa)
Compared to Circl, it also includes information about
- documentation
- dependencies
- how to build from source (not really relevant for us)
- a table of contents for the readme itself

## What info we want to include in the Readme
So what I think makes sense for us would be (in the order that seems sensible at first glance):
- Badge indicating status of tests at least. Code coverage could be worth thinking about but we would need some tooling to support that.
- A table of contents. I really like this for non-trivial readmes.
- Short overview of what the library offers and what its purpose / goal is. Mentioning the usage of the Math library is also good here since you will probably need to use both together to implement anything.
- A Security Disclaimer
- A succinct "how to install": This could link to the maven central page as well as have examples of how to add it to the Maven/Gradle dependency configurations.
- Information about version numbering. We use semver as well.
- We could link to our changelog once that exists somewhere at this point
- Link to the documentation; perhaps even to specific relevant topics.
- Implemented schemes and functionality in more detail, perhaps an example somewhere around here as well like we already had

Towards the bottom I would include more technical stuff that might not be as interesting to most users such as:
- Dependency information
- How to contribute: Link to the page in the docs about contributing
- Link to the License
- References

**Comment by feidens** [comment]
One additional question.
* Should we mention the funding of the CRC?

**Comment by JanBobolz** [comment]
Great writeup, @rheitjoh !

General question: how do we decide what info we put on the github.io page vs the README.MD ?

My thoughts:

- It feels weird to have some important info only in the readme and not on the github.io page. I wouldn't expect to have to search in the repo's readme for anything if I've already found the _official documentation website_ (or is that a weird expectation?) 
- I'd say putting updatable data in _both_ is probably a slight pain for us in the future (unless there's a technical solution to automatically "sync" those). 

Any thoughts on this? Any good ideas how to separate what fits into the README and what gets onto the github.io page? 

> Should we mention the funding of the CRC?

Sure, sounds fair.

**Comment by rheitjoh** [comment]
A good question.
I think having stuff mostly in the docs and linking from each project's readme makes most sense since that makes the information less fragmented for us as developers, i.e. we don't need to keep monitoring the readmes for accuracy.
Plus, as you said, the *official documentation* page should contain all the info you need and the readme is more meant to quickly point you to relevant information.

**Comment by feidens** [comment]
[RELIC](https://github.com/relic-toolkit/relic#readme) has also interesting banners and is is an example for a very short readme
