### ISSUE TITLE
Release CI scheduled action is triggered on wrong branch

### ISSUE THREAD

**Issue by rheitjoh** [cryptimeleon/craco#71]
The nightly scheduled release CI action gets triggered on the default branch (develop), leading to [this failure](https://github.com/cryptimeleon/craco/actions/runs/776086497). It should be triggered only on release branches, however. But, the `on.schedule` attribute does not support specifying a specific branch to schedule on. 

I see two ways to solve this issue:

1. One can specify a branch to check out for the checkout action (in this case master). However, this would conflict with the `on.push` trigger for `release/**` branches, i.e. those would also be tested on the master branch. So I would need to either split off the scheduled action into its own action, or figure out whether one can pass the `ref` argument to the checkout action only if the action is scheduled.

2. Just remove the scheduling for the release CI. After all, the release versions are not going to suddenly change and break other branches. Release versions are always coordinated to work with each other.  

I am currently in favor of the first option and just splitting the scheduled action off into its own action. I think its nice to frequently be checking the release version for compatibility, even if there shouldn't be any problems. But maybe I am just paranoid.

This issue also applies to all the other projects with a release CI, i.e. Predenc, Math, Mclwrap, and Groupsig.

**Comment by JanBobolz** [comment]
I'm okay with either option 👍

**Comment by feidens** [comment]
vote for 1.
