### ISSUE TITLE
Add journal of crypto reference to SPSEQ scheme

### ISSUE THREAD

**Issue by feidens** [cryptimeleon/craco#76]
We should also cite the JC version in [SPSEQSignatureScheme](https://github.com/cryptimeleon/craco/blob/ddda04e9498f3be40ad7c34e3f7f74b7f0b64592/src/main/java/org/cryptimeleon/craco/sig/sps/eq/SPSEQSignatureScheme.java)

```
Article{JC:FucHanSla19,
  author =       "Georg Fuchsbauer and
                  Christian Hanser and
                  Daniel Slamanig",
  title =        "Structure-Preserving Signatures on Equivalence Classes and Constant-Size Anonymous Credentials",
  pages =        "498--546",
  volume =       32,
  month =        apr,
  publisher =    springer,
  year =         2019,
  journal =      jcrypto,
  number =       2,
  doi =          "10.1007/s00145-018-9281-4",
}
```

**Comment by rheitjoh** [comment]
Currently we are citing Hanser and Slamanig in the readme. Is that wrong or should we be citing both?

**Comment by feidens** [comment]
As I see it the version that we cite is also not the correct one. The fixed version also on eprint has Fuchsbauer as an additional author, see https://eprint.iacr.org/2014/944.pdf.
Hence I would vote for just citing the JoC version.
